In [2]:
import numpy as np
import pandas as pd
from pathlib import Path

In [ ]:
variables = np.array (['Costos','Ingresos','Utilidad'])
aleatorios = np.random.randint (100000, 800000, size=(1000, len(variables)))

data = pd.DataFrame (aleatorios, columns = variables)
print (data.head(11))
print (data.shape)

    Costos  Ingresos  Utilidad
0   512150    207828    447795
1   315775    758876    303253
2   415616    514655    607420
3   255211    656263    220715
4   707131    325702    726912
5   515980    322241    464050
6   745404    323380    346842
7   639102    150246    719207
8   534133    527690    129990
9   176788    514716    669381
10  586462    398630    336893
(1000, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Costos    1000 non-null   int32
 1   Ingresos  1000 non-null   int32
 2   Utilidad  1000 non-null   int32
dtypes: int32(3)
memory usage: 11.8 KB
None


In [20]:
nombre = 'Jeremy '
print (nombre)

nombre = nombre.strip()
print(f'El nombre sin espacios al principio y al final queda como: {nombre}')

Jeremy 
El nombre sin espacios al principio y al final queda como: Jeremy


In [6]:
#Escribe un programa que solicite dos números enteros e imprima todos los números enteros entre ellos.
numero1 = int(input('Por favor ingrese un numero'))
numero2 = int(input('Por favor ingrese otro numero'))

if numero1 < numero2:
    for i in range (numero1+1,numero2):
        print (f'la diferencias entre los numeros son: {i}')
elif numero1 > numero2:
    for i in range (numero2+1,numero1):
        print (f'la diferencia entre los numeros son: {i}')
else:
    print ('Los numeros son iguales')

la diferencia entre los numeros son: 4
la diferencia entre los numeros son: 5
la diferencia entre los numeros son: 6
la diferencia entre los numeros son: 7


In [10]:
'''Escribe un programa para calcular cuántos días tomará que la colonia de una bacteria A supere o iguale a la colonia de una bacteria B,
basado en tasas de crecimiento del 3% y 1.5%, respectivamente.
Supón que la colonia A comienza con 4 elementos y B con 10.
'''
bacteriaA = 4
bacteriaB = 10
dias = 0

while bacteriaA <= bacteriaB and dias < 1000:
    bacteriaA *= 1.03
    bacteriaB *= 1.015
    dias += 1

print (f'La bacteria A superará a la B en {dias} días')

La bacteria A superará a la B en 63 días


In [16]:
'''Para procesar una cantidad de 15 datos de evaluaciones de usuarios de un servicio de la empresa,
necesitamos verificar si las calificaciones son válidas. Por lo tanto, escribe un programa que recibirá
calificaciones del 0 al 5 y verificará si son valores válidos. Si se ingresa una calificación superior a 5 o inferior a 0,
se repetirá hasta que el usuario ingrese un valor válido.
'''
for i in range (15):
    calificaciones = float(input('Por favor ingrese la calificación del usuario'))

    while calificaciones < 0 or calificaciones > 5:
        calificaciones = float(input(f'Las notas no son válidas, por favor ingresa las calificaciones del usuario {i}: '))

print ('Verificaciones completadas, son todas las notas válidas')




ValueError: could not convert string to float: ''

In [20]:
'''Desarrolla un programa que lea un conjunto indefinido de temperaturas en grados Celsius y calcule su promedio.
La lectura debe detenerse al ingresar el valor -273°C.
'''
valor_error = float(-273)
temperaturas = 0

for i in range (1,21):
    temperaturas = float(input(f'Ingrese la temperatura n{i}: '))
    
    if i == 20:
        print (f'el promedio de las temperaturas es de: {temperaturas/i}')
    elif temperaturas == valor_error:
        print ('No puede ingresar esa temperatura')
    else:
        continue



No puede ingresar esa temperatura
No puede ingresar esa temperatura


KeyboardInterrupt: Interrupted by user

In [22]:
#Escribe un programa que calcule el factorial de un número entero proporcionado por el usuario.

numero = int(input('Ingrese un numero por favor, sólo uno: '))

if numero > 0:
    factorial = 1
    for i in range (1, numero+1):
        factorial *= i
    
    print (f'El factorial de tu número {numero} es: {factorial}')
else:
    print ('No puede ser un número negativo')


El factorial de tu número 4 es: 24


In [ ]:
import numpy as np
import pandas as pd

In [7]:
INGRESOS = np.random.randint(1000, 5000, size=12)
COSTOS = np.random.randint(500, 3000, size=12)
UTILIDAD = INGRESOS - COSTOS
MESES = ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre']

data = np.column_stack((INGRESOS, COSTOS, UTILIDAD))
df = pd.DataFrame(data, columns=['INGRESOS', 'COSTOS', 'UTILIDAD'])

print (df.head(12))

print (data)

    INGRESOS  COSTOS  UTILIDAD
0       3999     983      3016
1       2314    1046      1268
2       3102    2358       744
3       3441    1305      2136
4       2880    1445      1435
5       3427    2471       956
6       2710    2526       184
7       1886    2555      -669
8       1263     717       546
9       4934    2207      2727
10      2941    1782      1159
11      1325     799       526
[[3999  983 3016]
 [2314 1046 1268]
 [3102 2358  744]
 [3441 1305 2136]
 [2880 1445 1435]
 [3427 2471  956]
 [2710 2526  184]
 [1886 2555 -669]
 [1263  717  546]
 [4934 2207 2727]
 [2941 1782 1159]
 [1325  799  526]]
